config/routes.rb
JobOps::Application.routes.draw do

  resources :communities, :only => [:index]
  get "/communities/twitter/:id", :controller => :communities, :action => :twitter_follow,:defaults => {:format => 'json'}, :as => :twitter_follow

  resources :industry, :only => [:index, :show]

  get "job_searches_user/new/", :controller => :job_searches_user, :action => :new, :defaults => { :format => 'json' }
  get "job_searches_user/:id", :controller => :job_searches_user, :action => :destroy, :defaults => {:format => 'json'}

  match 'jobs/dashboard' => 'jobs#dashboard', :as => :jobs_dashboard

  resources :jobs, :only => [:index, :show]
  get "/jobs/flag/:id", :controller => :jobs, :action => :flag, :defaults => { :format => 'json' }, :as => :flag_job

  resources :careers, :only => [:index, :show]
  get "/careers/flag/:id", :controller => :careers, :action => :flag, :defaults => { :format => 'json' }, :as => :flag_career

  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#auth_failure'
  match '/auth/facebook/setup', :to => 'facebook#setup'

  get "settings/index"

  resources :resume, :only => [:index, :edit, :update]

  get "account/index"

  resources :awards

  resources :wars

  resources :languages

  resources :trainings

  resources :certifications

  resources :skills

  resources :educations

  resources :job_histories

  root :to => "home#index"

  devise_for :admins

  devise_for :users, :controllers => { :registrations => 'registrations' }

  resources :users

end

app/models/training.rb
class Training < ActiveRecord::Base
  belongs_to :user
  has_one :user
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  before_filter :authenticate_user!

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @trainings }
    end
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training = Training.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @training }
    end
  end

  # GET /trainings/new
  # GET /trainings/new.json
  def new
    @training = Training.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @training }
    end
  end

  # GET /trainings/1/edit
  def edit
    @training = Training.find(params[:id])
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = User.find_by_id(current_user.id).trainings.new(params[:training])

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, :notice => 'Training was successfully created.' }
        format.json { render :json => @training, :status => :created, :location => @training }
      else
        format.html { render :action => "new" }
        format.json { render :json => @training.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trainings/1
  # PUT /trainings/1.json
  def update
    @training = Training.find(params[:id])

    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to @training, :notice => 'Training was successfully updated.' }
        format.json { render :json => @training }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @training.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training = Training.find(params[:id])
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { render :json => @training }
    end
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.haml
= form_for @training do |f|
  - if @training.errors.any?
    #error_explanation
      %h2= "#{pluralize(@training.errors.count, "error") } prohibited this training from being saved:"
      %ul
        - @training.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :training
    %br
    = f.text_field :training

  .field
    = f.label :training_date
    %br
    = f.date_select :training_date

  .actions
    = f.submit

app/views/trainings/edit.html.haml
#home
  %h1 Editing training

  = render 'form'

  = link_to 'Show', @training
  \|
  = link_to 'Back', trainings_path

app/views/trainings/index.html.haml
#home
  %h1 Listing trainings
  %table
    %tr
      %th Training
      %th Training date
      %th
      %th
      %th

    - @trainings.each do |training|
      %tr
        %td= training.training
        %td= training.training_date
        %td= link_to 'Show', training
        %td= link_to 'Edit', edit_training_path(training)
        %td= link_to 'Destroy', training, :confirm => 'Are you sure?', :method => :delete

  %br

  = link_to 'New Training', new_training_path

app/views/trainings/new.html.haml
#home
  %h1 New training

  = render 'form'
  = link_to 'Back', trainings_path

app/views/trainings/show.html.haml
#home
  %p#notice= notice

  %p
    %strong Training:
    = @training.training

  %p
    %strong Training date:
    = @training.training_date

  = link_to 'Edit', edit_training_path(@training)
  \|
  = link_to 'Back', trainings_path