config/routes.rb
JobOps::Application.routes.draw do

  resources :communities, :only => [:index]
  get "/communities/twitter/:id", :controller => :communities, :action => :twitter_follow,:defaults => {:format => 'json'}, :as => :twitter_follow

  resources :industry, :only => [:index, :show]

  get "job_searches_user/new/", :controller => :job_searches_user, :action => :new, :defaults => { :format => 'json' }
  get "job_searches_user/:id", :controller => :job_searches_user, :action => :destroy, :defaults => {:format => 'json'}

  match 'jobs/dashboard' => 'jobs#dashboard', :as => :jobs_dashboard

  resources :jobs, :only => [:index, :show]
  get "/jobs/flag/:id", :controller => :jobs, :action => :flag, :defaults => { :format => 'json' }, :as => :flag_job

  resources :careers, :only => [:index, :show]
  get "/careers/flag/:id", :controller => :careers, :action => :flag, :defaults => { :format => 'json' }, :as => :flag_career

  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#auth_failure'
  match '/auth/facebook/setup', :to => 'facebook#setup'

  get "settings/index"

  resources :resume, :only => [:index, :edit, :update]

  get "account/index"

  resources :awards

  resources :wars

  resources :languages

  resources :trainings

  resources :certifications

  resources :skills

  resources :educations

  resources :job_histories

  root :to => "home#index"

  devise_for :admins

  devise_for :users, :controllers => { :registrations => 'registrations' }

  resources :users

end

app/models/award.rb
class Award < ActiveRecord::Base
  belongs_to :user
  has_one :user
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController

 before_filter :authenticate_user!

  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @awards }
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @award = Award.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @award }
    end
  end

  # GET /awards/new
  # GET /awards/new.json
  def new
    @award = Award.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @award = Award.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = User.find_by_id(current_user.id).awards.new(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, :notice => 'Award was successfully created.' }
        format.json { render :json => @award, :status => :created, :location => @award }
      else
        format.html { render :action => "new" }
        format.json { render :json => @award.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.json
  def update
    @award = Award.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to @award, :notice => 'Award was successfully updated.' }
        format.json { render :json => @award }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @award.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = Award.find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to awards_url }
      format.json { render :json => @award }
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.haml
= form_for @award do |f|
  - if @award.errors.any?
    #error_explanation
      %h2= "#{pluralize(@award.errors.count, "error")} prohibited this award from being saved:"
      %ul
        - @award.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :award
    = f.text_field :award

  .field
    = f.label :award_date
    = f.date_select :award_date

  .actions
    = f.submit 'Save'

app/views/awards/edit.html.haml
#home
  %h1 Editing award
  = render 'form'

  = link_to 'Show', @award
  \|
  = link_to 'Back', awards_path

app/views/awards/index.html.haml
#home
  %h1 Listing awards
  %table
    %tr
      %th Award
      %th Award date
      %th
      %th
      %th

    - @awards.each do |award|
      %tr
        %td= award.award
        %td= award.award_date
        %td= link_to 'Show', award
        %td= link_to 'Edit', edit_award_path(award)
        %td= link_to 'Destroy', award, :confirm => 'Are you sure?', :method => :delete


  %br
  = link_to 'New Award', new_award_path

app/views/awards/new.html.haml
#home
  %h1 New award

  = render 'form'

  = link_to 'Back', awards_path

app/views/awards/show.html.haml
#home
  %p#notice= notice

  %p
    %strong Award:
    = @award.award

  %p
    %strong Award date:
    = @award.award_date

  = link_to 'Edit', edit_award_path(@award)
  \|
  = link_to 'Back', awards_path