config/routes.rb
JobOps::Application.routes.draw do

  resources :communities, :only => [:index]
  get "/communities/twitter/:id", :controller => :communities, :action => :twitter_follow,:defaults => {:format => 'json'}, :as => :twitter_follow

  resources :industry, :only => [:index, :show]

  get "job_searches_user/new/", :controller => :job_searches_user, :action => :new, :defaults => { :format => 'json' }
  get "job_searches_user/:id", :controller => :job_searches_user, :action => :destroy, :defaults => {:format => 'json'}

  match 'jobs/dashboard' => 'jobs#dashboard', :as => :jobs_dashboard

  resources :jobs, :only => [:index, :show]
  get "/jobs/flag/:id", :controller => :jobs, :action => :flag, :defaults => { :format => 'json' }, :as => :flag_job

  resources :careers, :only => [:index, :show]
  get "/careers/flag/:id", :controller => :careers, :action => :flag, :defaults => { :format => 'json' }, :as => :flag_career

  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#auth_failure'
  match '/auth/facebook/setup', :to => 'facebook#setup'

  get "settings/index"

  resources :resume, :only => [:index, :edit, :update]

  get "account/index"

  resources :awards

  resources :wars

  resources :languages

  resources :trainings

  resources :certifications

  resources :skills

  resources :educations

  resources :job_histories

  root :to => "home#index"

  devise_for :admins

  devise_for :users, :controllers => { :registrations => 'registrations' }

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name,
                  :location, :phone, :goal, :relocate, :desired_salary, :gender,
                  :ethnicity, :family, :dob, :military_status, :service_branch, :moc,
                  :rank, :disability, :security_clearance, :unit, :resume, :avatar,
                  :privacy_settings, :email_settings

  serialize :email_settings
  serialize :privacy_settings

  has_many :awards
  has_many :authentications
  has_many :careers, :through => :career_users
  has_many :career_users
  has_many :certifications
  has_many :job_histories
  has_many :educations
  has_many :languages
  has_many :skills
  has_many :trainings
  has_many :wars
  has_many :job_searches_user
  has_many :job_searches, :through => :job_searches_user
  has_many :job_users
  has_many :jobs, :through => :job_users
  validates_presence_of :name

  before_save :add_saved_search

  def add_saved_search
    if self.moc_changed?
      if !self.moc.blank?
        if self.location?
          job_search = JobSearch.where(:keyword => self.moc, :location => self.location)
          job_search = JobSearch.create(:keyword => self.moc, :location => self.location, :search_params => {"job_searches_keyword_contains"=> self.moc, "job_searches_location_contains"=> self.location}) unless !job_search.blank?
          job_search.delay(:priority => 10).search
        else
          job_search = JobSearch.where(:keyword => self.moc)
          job_search = JobSearch.create(:keyword => self.moc) unless !job_search.blank?
        end

        if job_search.is_a?(Array)
          job_search.each { |job| job.delay(:priority => 10).search}
        else
        job_search.delay(:priority => 10).search
        end

        self.job_searches << job_search

        careers = Career.new.futures_pipeline
        career_by_moc = careers.search(self.moc)

        unless career_by_moc.nil?
          career_by_moc.each do |career|
            if self.location?
              job_search = JobSearch.where(:keyword => career.title, :location => self.location)
              job_search = JobSearch.create(:keyword => career.title, :location => self.location, :search_params => {"job_searches_keyword_contains"=> career.title, "job_searches_location_contains"=> self.location} ) unless !job_search.blank?
            else
              job_search = JobSearch.where(:keyword => career.title)
              job_search = JobSearch.create(:keyword => career.title) unless !job_search.blank?
            end
            self.job_searches << job_search
            if job_search.is_a?(Array)
              job_search.each { |job| job.delay(:priority => 10).search}
            else
            job_search.delay(:priority => 10).search
            end
          end
        end
      end
    end
  end

  def apply_omniauth(omniauth, save_it = false)
    if omniauth['user_info']
      self.name = omniauth['user_info']['name'] if omniauth['user_info']['name']
      self.location = omniauth['user_info']['location'] if omniauth['user_info']['location']
    end
    case omniauth['provider']
      when 'facebook'
        self.apply_facebook(omniauth)
      when 'linked_in'
        self.apply_email(omniauth)
      when 'twitter'
        self.apply_email(omniauth)
      end
    self.email = omniauth['user_info']['email'] if email.blank?
    build_authentications(omniauth, save_it)
  end

  def build_authentications(omniauth, save_it = false)
    auth_params = { :provider => omniauth['provider'],
                    :uid => omniauth['uid'],
                    :access_token => omniauth['credentials']['token'],
                    :access_secret => omniauth['credentials']['secret'],
    }
    if save_it
      authentications.create!(auth_params)
    else
      authentications.build(auth_params)
    end
  end

  def apply_omniauth!(omniauth)
    apply_omniauth(omniauth, true)
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

  def age(dob, now = Time.now.utc.to_date)
      now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def twitter_user
    unless authentications.where(:provider => "twitter").first.nil?
      twitter_client
    end
  end

  def facebook_user
    unless authentications.where(:provider => "facebook").first.nil?
      facebook_client
    end
  end

  def add_facebook_info
    @fb_info = facebook_user.fetch

    #Pull in basic profile information
    self.location = @fb_info.location.name if @fb_info.location
    self.dob = @fb_info.birthday if @fb_info.birthday
    self.gender = @fb_info.gender

    #Pull work history
    @work = @fb_info.work
    @work.each do |work|
      job_history = job_histories.new
      job_history.org_name = work.employer.name
      job_history.title = work.position.name if work.position
      job_history.summary = work.description if work.description
      job_history.start_date = work.start_date if work.start_date
      job_history.end_date = work.end_date if work.end_date
      job_history.save
    end

    #Pull education history
    @education = @fb_info.education
    @education.each do |edu|
      education = educations.new
      education.school_name = edu.school.name
      education.degree = edu.degree.name if edu.degree
      education.study_field = edu.concentration.first.name if !edu.concentration.empty?
      education.end_date = Date.new(edu.year.name.to_i) if edu.year
      education.save
    end
  end

  def linked_in_user
    unless authentications.where(:provider => "linked_in").first.nil?
      linked_in_client
    end
  end

  def add_linked_in_info
    @linked_in_profile = linked_in_client.profile

    #Basic Information
    self.phone = @linked_in_profile.phone_numbers.all.first.phone_number unless @linked_in_profile.phone_numbers.nil?

    if @linked_in_profile.dateOfBirth.nil?
      self.dob = nil
    else
      self.dob = Date.new(@linked_in_profile.dateOfBirth.year,
                        @linked_in_profile.dateOfBirth.month,
                        @linked_in_profile.dateOfBirth.day)
    end

    #Pull work history
    @work = @linked_in_profile.positions
    unless @work.nil?
      @work.all.each do |work|
        job_history = job_histories.new
        job_history.org_name = work.company.name
        job_history.title = work.title
        job_history.summary = work.summary
        job_history.start_date = Date.new(work.start_date.year,work.start_date.month)
        unless work.end_date.nil?
          job_history.end_date = Date.new(work.end_date.year,work.end_date.month)
        end
        job_history.save
      end
    end

    #Pull Education history
    @education = @linked_in_profile.educations
    unless @education.nil?
      @education.all.each do |edu|
        education = educations.new
        education.school_name = edu.school_name
        education.degree = edu.degree
        education.study_field = edu.field_of_study
        education.start_date = Date.new(edu.start_date.year)
        education.end_date = Date.new(edu.end_date.year)
        education.activities = edu.activities
        education.notes = edu.notes
        education.save
      end
    end

    #Pull Certifications
    @cert = @linked_in_profile.certifications
    unless @cert.nil?
      @cert.all.each do |certification|
        cert = certifications.new
        cert.name = certification.certification.name
        cert.save
      end
    end

    #Pull Languages
    @language = @linked_in_profile.languages
    unless @language.nil?
      @language.all.each do |linked_in_language|
        language = languages.new
        language.language = linked_in_language.language.name
        language.save
      end
    end

    #Pull Skills
    @skill = @linked_in_profile.skills
    unless @skill.nil?
      @skill.all.each do |linked_in_skill|
        user_skill = skills.new
        user_skill.skill = linked_in_skill.skill.name
        user_skill.save
      end
    end
  end

  def twitter_user
    if not authentications.where(:provider => "twitter").first.nil?
      twitter_client
    end
  end

  protected

  def apply_facebook(omniauth)
    if (extra = omniauth['extra']['user_hash'] rescue false)
      self.email = (extra['email'] rescue '')
      self.password = Devise.friendly_token[0,20]
    end
  end

  def apply_email(omniauth)
    #Create a fake email address using LinkedIn uid
    self.email = "change-me-#{omniauth['uid']}@jobops.us"
    self.password = Devise.friendly_token[0,20]
  end

  def linked_in_client
    linked_in_auth = authentications.where(:provider => "linked_in").first
    LinkedIn.configure do |config|
      config.token = ENV['LINKEDIN_KEY']
      config.secret = ENV['LINKEDIN_SECRET']
      config.default_profile_fields = ['certifications','date-of-birth','educations',
        'phone-numbers','positions','picture-url','skills','summary']
    end
    linked_in = LinkedIn::Client.new
    linked_in.authorize_from_access(linked_in_auth.access_token, linked_in_auth.access_secret)
    linked_in_client ||= linked_in
  end

  def twitter_client
    Twitter.configure do |config|
      config.consumer_key = ENV['TWITTER_KEY']
      config.consumer_secret = ENV['TWITTER_SECRET']
      config.oauth_token = authentications.where(:provider => "twitter").first.access_token
      config.oauth_token_secret = authentications.where(:provider => "twitter").first.access_secret
    end
    twitter_client ||= Twitter::Client.new
  end

  def facebook_client

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def index
    @user = User.find_by_id(current_user.id)
    @twitter_user = @user.twitter_user
    @facebook_user = @user.facebook_user
    if !@facebook_user.nil?
      @facebook_user = @facebook_user.fetch
    end
    render :template => 'users/profile/show'
  end

  def show
    @user = User.find_by_id(current_user.id)
    @twitter_user = @user.twitter_user
    render :template => 'users/profile/show'
  end

  def edit
    @user = User.find_by_id(current_user.id)
    render :template => 'users/profile/edit'
  end

  def update
    @user = User.find_by_id(current_user.id)

    respond_to do |format|
         if @user.update_attributes(params[:user])
           format.html { redirect_to(edit_user_path(@user), :notice => 'User was successfully updated.') }
           #format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
           format.xml  { head :ok }
         else
           format.html { render :action => "edit" }
           format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
         end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def profile_location_tip
    "This field will be used in help focus your job search to jobs within your proximity."
  end
  def profile_phone_tip
  end
  def profile_goal_tip
  end
  def profile_relocate_tip
  end
  def profile_desired_salary_tip
  end
  def linkedin_tip
  "some content here"
  end
end

app/views/users/profile/_award.html.haml
%h3 - Awards
.ive-got-a-button-wrapper
  .tab-add-edit
    %span= link_to 'Add new award', new_award_path, :class => "add_award add_form_button"
  %br.clearit
  .tab_form
    %ul.award
      -current_user.awards.each do |award|
        %li
          %div{:class=>"award_#{award.id} display_wrapper"}
            %span
              =award.award
            =link_to ' ', award, :confirm => 'Are you sure?', :class=>"delete_link"
            %a{:class=>"award_#{award.id} edit_link"} Edit
          %div{:class=>"edit_award_#{award.id} edit_form"}
            =form_for award, :remote => true, :html => {:class => "edit_award"} do |f|
              =f.text_field :award
              =f.submit :value=>"Save", :class => "green-btn"
              %a{:class => 'cancel_edit_button', :href => '#'}Cancel
    .inline_form
      =form_for @user.awards.new, :remote => true do |f|
        =f.text_field :award
        =f.submit :value=>"Add Award", :class => "green-btn"
        %a{:class=>"cancel_form_button", :href => "#"} Cancel
  %script
    var award_meta = { display: ['award'] };

app/views/users/profile/_certifications.html.haml
%h3 - Certifications
.ive-got-a-button-wrapper
  .tab-add-edit
    %span= link_to 'Add new certification', new_certification_path, :class => "add_certification add_form_button"
  %br.clearit
  .tab_form
    %ul.certification
      -current_user.certifications.each do |certification|
        %li
          %div{:class=>"certification_#{certification.id} display_wrapper"}
            %span
              =certification.name
              =certification.institution
              - unless certification.date_acquired.nil?
                =certification.date_acquired.strftime("%Y")
            =link_to ' ', certification, :confirm => 'Are you sure?', :class=>"delete_link"
            %a{:class=>"certification_#{certification.id} edit_link"} Edit
          %div{:class=>"edit_certification_#{certification.id} edit_form"}
            =form_for certification, :remote => true, :html => {:class => "edit_certification"} do |f|
              =f.text_field :name
              =f.text_field :institution
              = f.date_select :date_acquired,
              :start_year => Time.now.year - 50,
              :discard_day => true,
              :discard_month => true,
              :include_blank => true
              =f.submit :value=>"Save", :class => "green-btn"
              %a{:class => 'cancel_edit_button', :href => '#'}Cancel
      .inline_form
        =form_for @user.certifications.new, :remote => true do |f|
          .field
            =f.label :name
            =f.text_field :name
          .field
            =f.label :institution
            =f.text_field :institution
          .field
            =f.label :date_acquired
            = f.date_select :date_acquired,
          :start_year => Time.now.year - 50,
          :discard_day => true,
          :discard_month => true,
          :include_blank => true
          .actions
            =f.submit :value=>"Add Certification", :class => "green-btn"
            %a{:class=>"cancel_form_button", :href => "#"} Cancel
  %script
    var certification_meta = { display: ['name','institution','date_acquired'] };

app/views/users/profile/_education.html.haml
%h3 - Education
.ive-got-a-button-wrapper
  .tab-add-edit
    %span= link_to 'Add Education', new_education_path, :class => "add_edu add_form_button"
  %br.clearit
  .tab_form
    %ul.education
      -Education.where(:user_id => current_user.id).each do |education|
        %li
          %div{ :class=>"education_#{education.id} display_wrapper"}
            %span
              =education.school_name
            %span.tab_function
              =link_to ' ', education, :confirm => 'Are you sure?', :class => 'delete_link'
              %a{ :class=> 'edit_education edit_link', :data => "education_#{education.id}"} Edit
            %br.clearit
            %ul
              %li.dates
                =education.start_date.strftime("%Y") unless education.start_date.nil?
                to
                =education.end_date.strftime("%Y")  unless education.start_date.nil?
              %li.study
                ="#{education.degree} in #{education.study_field}"
          %div{ :class=>'edit_form' }
            -@education = education
            =render "educations/form"
            %a{:class => 'cancel_edit_button', :href => '#'}Cancel
    .inline_form
      -@education = current_user.educations.new
      =render "educations/form"
      %a{:class=>"cancel_form_button", :href => "#"} Cancel
  %script
    var education_meta = { display: ['school_name','start_date','end_date','degree','study_field'] };

app/views/users/profile/_experience.html.haml
%h3 - Job History
.ive-got-a-button-wrapper
  .tab-add-edit
    %span= link_to 'Add a job', new_job_history_path, :class => "add_job add_form_button"
  %br.clearit
  .tab_form
    %ul.job
      -current_user.job_histories.each do |job|
        %li
          %div{:class=>"job_#{job.id} display_wrapper"}
            %span
              = job.title
              at
              = job.org_name
              =link_to ' ', job, :confirm => 'Are you sure?', :class=>"delete_link"
              %a{:class=>"job_#{job.id} edit_link"} Edit
          %div{:class=>"edit_job_#{job.id} edit_form"}
            -@job_history = job
            =render "job_histories/form"
            %a{:class => 'cancel_edit_button', :href => '#'}Cancel

    .inline_form
      -@job_history = current_user.job_histories.new
      =render "job_histories/form"
      %a{:class=>"cancel_form_button", :href => "#"} Cancel
  %script
    var job_meta = { display: ['title','org_name'] };

app/views/users/profile/_form.html.haml
= form_for(@user, :html => { :multipart => true }) do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    .field-wrap
      = f.label :name
      = f.text_field :name, :class => 'required'
  .field
    = f.label :location
    = f.text_field :location
    .helpful_info
      = profile_location_tip
  .field
    = f.label :phone
    = f.text_field :phone
    .helpful_info
      = profile_phone_tip
  .field
    = f.label :goal
    = f.text_field :goal
    .helpful_info
      = profile_goal_tip
  .field
    = f.label :relocate
    = f.text_field :relocate
    .helpful_info
      = profile_relocate_tip
  .field
    = f.label :desired_salary
    = f.text_field :desired_salary
    .helpful_info
      = profile_desired_salary_tip
  .actions
    =f.submit "Submit", :value=>"Save", :class => "green-btn"

app/views/users/profile/_languages.html.haml
%h3 - Languages
.ive-got-a-button-wrapper
  .tab-add-edit
    %span= link_to 'Add new language', new_language_path, :class => "add_language add_form_button"
  %br.clearit
  .tab_form
    %ul.language
      -current_user.languages.each do |language|
        %li
          %div{:class=>"language_#{language.id} display_wrapper"}
            %span
              =language.language
            =link_to ' ', language, :confirm => 'Are you sure?', :class=>"delete_link"
            %a{:class=>"language_#{language.id} edit_link"} Edit
          %div{:class=>"edit_language_#{language.id} edit_form"}
            =form_for language, :remote => true, :html => {:class => "edit_skill"} do |f|
              =f.text_field :language
              =f.submit :value=>"Save", :class => "green-btn"
              %a{:class => 'cancel_edit_button', :href => '#'}Cancel
    .inline_form
      =form_for @user.languages.new, :remote => true do |f|
        =f.text_field :language
        =f.submit :value=>"Add Language", :class => "green-btn"
        %a{:class=>"cancel_form_button", :href => "#"} Cancel
  %script
    var language_meta = { display: ['language'] };

app/views/users/profile/_nav_profile.html.haml
%h2#name= @user.name

%ul.profile_nav
  %li= active_link_to "View Profile", users_path, :active => :exclusive
  %li= active_link_to "Edit Profile", edit_user_path(@user.id)
  %li= active_link_to "Account Settings", :controller => "account", :action => "index"

app/views/users/profile/_personal_form.html.haml
%h3 Personal Info
= form_for(@user) do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :dob
    = f.date_select :dob,
    :start_year => Time.now.year - 75,
    :end_year => Time.now.year - 16

  .field
    = f.label :gender
    = f.text_field :gender

  .field
    = f.label :ethnicity
    = f.text_field :ethnicity

  .field
    = f.label :family
    = f.text_field :family

  .actions
    = f.submit

app/views/users/profile/_sidebar_nav.html.haml
%ul.tabs
  %li.user-basic
    %a{:href =>"#basic_info"} General Info
  %li.user-military
    %a{:href => "#military_info"} Military Info
  %li.user-survey
    %a{:href => "#career_survey"} Career Survey
  %li.user-skills
    %a{:href => "#skills_edu"} Skills &amp; Education
  %li.user-experience
    %a{:href => "#exp"} Experience

app/views/users/profile/_skills.html.haml
%h3 - Skills
.ive-got-a-button-wrapper
  .tab-add-edit
    %span= link_to 'Add New Skill', new_skill_path, :class => "add_skill add_form_button"
  %br.clearit
  .tab_form
    %ul.skill
      -current_user.skills.each do |skill|
        %li
          %div{:class=>"skill_#{skill.id} display_wrapper"}
            %span
              =skill.skill
            =link_to ' ', skill, :confirm => 'Are you sure?', :class=>"delete_link"
            %a{:class=>"skill_#{skill.id} edit_link"} Edit
          %div{:class=>"edit_skill_#{skill.id} edit_form"}
            =form_for skill, :remote => true, :html => {:class => "edit_skill"} do |f|
              =f.text_field :skill
              =f.submit :value=>"Save", :class => "green-btn"
              %a{:class => 'cancel_edit_button', :href => '#'}Cancel
    .inline_form
      =form_for @user.skills.new, :remote => true do |f|
        =f.text_field :skill
        =f.submit :value=>"Add Skill", :class => "green-btn"
        %a{:class=>"cancel_form_button", :href => "#"} Cancel
  %script
    var skill_meta = { display: ['skill'] };

app/views/users/profile/_trainings.html.haml
%h3 - Trainings
.ive-got-a-button-wrapper
  .tab-add-edit
    %span= link_to 'Add new training', new_training_path, :class => "add_training add_form_button"
  %br.clearit
  .tab_form
    %ul.training
      -current_user.trainings.each do |training|
        %li
          %div{:class=>"training_#{training.id} display_wrapper"}
            %span
              =training.training
              - unless training.training_date.nil?
                =training.training_date.strftime("%Y")
            =link_to ' ', training, :confirm => 'Are you sure?', :class=>"delete_link"
            %a{:class=>"training_#{training.id} edit_link"} Edit
          %div{:class=>"edit_training_#{training.id} edit_form"}
            =form_for training, :remote => true, :html => {:class => "edit_training"} do |f|
              =f.text_field :training
              =f.date_select :training_date, :start_year => Time.now.year - 50, :discard_day => true, :discard_month => true, :include_blank => true
              =f.submit :value=>"Save", :class => "green-btn"
              %a{:class => 'cancel_edit_button', :href => '#'}Cancel
    .inline_form
      =form_for @user.trainings.new, :remote => true do |f|
        .field
          =f.label :training
          =f.text_field :training
        .field
          =f.label :training_date
          = f.date_select :training_date, :start_year => Time.now.year - 50, :discard_day => true, :discard_month => true, :include_blank => true
        .actions
          =f.submit :value=>"Add Training", :class => "green-btn"
          %a{:class=>"cancel_form_button", :href => "#"} Cancel
  %script
    var training_meta = { display: ['training','training_date'] };

app/views/users/profile/_war.html.haml
%h3 - Wars
.ive-got-a-button-wrapper
  .tab-add-edit
    %span= link_to 'Add new war', new_war_path, :class => "add_war add_form_button"
  %br.clearit
  .tab_form
    %ul.war
      -current_user.wars.each do |war|
        %li
          %div{:class=>"war_#{war.id} display_wrapper"}
            %span
              =war.war
            =link_to ' ', war, :confirm => 'Are you sure?', :class=>"delete_link"
            %a{:class=>"war_#{war.id} edit_link"} Edit
          %div{:class=>"edit_war_#{war.id} edit_form"}
            =form_for war, :remote => true, :html => {:class => "edit_war"} do |f|
              =f.text_field :war
              =f.submit :value=>"Save", :class => "green-btn"
              %a{:class => 'cancel_edit_button', :href => '#'}Cancel
    .inline_form
      =form_for @user.wars.new, :remote => true do |f|
        =f.text_field :war
        =f.submit :value=>"Add War", :class => "green-btn"
        %a{:class=>"cancel_form_button", :href => "#"} Cancel
  %script
    var war_meta = { display: ['war'] };

app/views/users/profile/edit.html.haml
#profile
  =render 'users/profile/nav_profile'
  %br.clearit
  #user-main
    =render 'users/profile/sidebar_nav'
    .tab_container
      #basic_info.tab_content
        %h2 General Info
        - unless @user.authentications.empty?
          = render 'authentications/connect_accounts'
        %br.clearit
        .tab_form
          =render 'users/profile/form'

      #military_info.tab_content
        %h2 Military Info
        %br.clearit
        .tab_form
          =render 'military/form'
        =render 'users/profile/war'
        =render 'users/profile/award'

      #skills_edu.tab_content
        %h2 Skills &amp; Education
        =render "users/profile/education"
        =render "users/profile/skills"
        =render "users/profile/languages"
        =render "users/profile/trainings"
        =render "users/profile/certifications"

      #exp.tab_content
        %h2 Experience
        =render "users/profile/experience"

    %br.clearit

app/views/users/profile/show.html.haml
#profile
  = render 'users/profile/nav_profile'
  %br.clearit
  #user-main
    .show_profile_sidebar
      - if not @facebook_user.nil?
        = image_tag @facebook_user.picture
      - if not @twitter_user.nil?
        = image_tag "http://img.tweetimag.es/i/#{@twitter_user.user.screen_name}_b"
      - unless @user.linked_in_user.nil?
        = image_tag @user.linked_in_user.profile.picture_url
    .tab_container
      #connect_accounts
        .connect_title
          Connect Your Accounts
        Pandas and gradient backgrounds increase transparency in local government through Twitter and #gov20. Oswald font is great for communication through scotch and San Francisco.
        .connect_icons
          Connect your accounts now:
          %span.fb_link
            = link_to "Facebook"
          %span.twit_link
            = link_to "Twitter"
          %span.li_link
            = link_to "LinkedIn"
      #basic_info
        %h2 General Info
        .tab_form
          .label
            Location:
          .value= @user.location
          .label
            Phone:
          .value= @user.phone
          .label
            Current Goal:
          .value= @user.goal
          .label
            Willingness to relocate:
          .value= @user.relocate
          .label
            Desired Salary:
          .value= @user.desired_salary
          %br.clearit

      #military_info
        %h2 Military Info
        .tab_form
          .label
            Current Status:
          .value= @user.military_status
          .label
            Service Branch:
          .value= @user.service_branch
          .label
            Rank/Pay grade:
          .value= @user.rank
          .label
            Last Unit:
          .value= @user.unit
          .label
            Veteran of:
          .value
            - @user.wars.each do |wars|
              = wars.war
          .label
            Awards:
          .value
            - @user.awards.each do |awards|
              = awards.award
          .label
            Disability:
          .value= @user.disability
          .label
            MOC:
          .value= @user.moc


          %br.clearit

      #skills_edu
        %h2 Skills &amp; Education
        %br.clearit
        %h3 - Education
        %br.clearit
        .tab_form
          - @user.educations.each do |education|
            .label
              School Name:
            .value= education.school_name
            .label
              Degree:
            .value= education.degree
            .label
              Study Field:
            .value= education.study_field
            .label
              Start Date:
            .value= education.start_date
            .label
              End Date:
            .value= check_present(education.end_date)
            .label
              Activities:
            .value= education.activities
            .label
              Notes:
            .value= education.notes
          %br.clearit

        %h3 - Skills
        .tab_form
          .label
            Skills:
          .value=@user.skills.map(&:skill).to_sentence
          %br.clearit

        %h3 - Languages
        .tab_form
          .label
            Languages:
          .value=@user.languages.map(&:language).to_sentence
          %br.clearit

        %h3 - Trainings
        .tab_form
          - @user.trainings.each do |training|
            .label
              Training:
            .value
              ="#{training.training}"
              - unless training.training_date.nil?
                "on #{training.training_date.strftime('%Y')}"
          %br.clearit

        %h3 - Certifications
        .tab_form
          - @user.certifications.each do |certification|
            .label
              Certification:
            .value
              = "#{certification.name} at #{certification.institution} "
              - unless certification.date_acquired.nil?
                "on #{certification.date_acquired.strftime('%Y')}"
          %br.clearit

      #exp
        %h2 Experience
        .tab_form
          - @user.job_histories.each do |job_history|
            .label
              Company:
            .value= job_history.org_name
            .label
              Title:
            .value= job_history.title
            .label
              Start:
            .value= job_history.start_date
            .label
              End:
            .value= check_present(job_history.end_date)
            .label
              Summary:
            .value=job_history.summary
          %br.clearit
    %br.clearit