config/routes.rb
JobOps::Application.routes.draw do

  resources :communities, :only => [:index]
  get "/communities/twitter/:id", :controller => :communities, :action => :twitter_follow,:defaults => {:format => 'json'}, :as => :twitter_follow

  resources :industry, :only => [:index, :show]

  get "job_searches_user/new/", :controller => :job_searches_user, :action => :new, :defaults => { :format => 'json' }
  get "job_searches_user/:id", :controller => :job_searches_user, :action => :destroy, :defaults => {:format => 'json'}

  match 'jobs/dashboard' => 'jobs#dashboard', :as => :jobs_dashboard

  resources :jobs, :only => [:index, :show]
  get "/jobs/flag/:id", :controller => :jobs, :action => :flag, :defaults => { :format => 'json' }, :as => :flag_job

  resources :careers, :only => [:index, :show]
  get "/careers/flag/:id", :controller => :careers, :action => :flag, :defaults => { :format => 'json' }, :as => :flag_career

  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#auth_failure'
  match '/auth/facebook/setup', :to => 'facebook#setup'

  get "settings/index"

  resources :resume, :only => [:index, :edit, :update]

  get "account/index"

  resources :awards

  resources :wars

  resources :languages

  resources :trainings

  resources :certifications

  resources :skills

  resources :educations

  resources :job_histories

  root :to => "home#index"

  devise_for :admins

  devise_for :users, :controllers => { :registrations => 'registrations' }

  resources :users

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user
  has_one :user

  validates_presence_of :school_name

  def valid_year(check_year)
    if not check_year.nil?
      check_year.year
    end
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

  before_filter :authenticate_user!

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @educations }
    end
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    @education = Education.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @education }
    end
  end

  # GET /educations/new
  # GET /educations/new.json
  def new
    @education = Education.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @education }
    end
  end

  # GET /educations/1/edit
  def edit
    @education = Education.find(params[:id])
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = User.find_by_id(current_user.id).educations.new(params[:education])

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, :notice => 'Education was successfully created.' }
        format.json { render :json => @education, :status => :created, :location => @education }
      else
        format.html { render :action => "new" }
        format.json { render :json => @education.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /educations/1
  # PUT /educations/1.json
  def update
    @education = Education.find(params[:id])

    respond_to do |format|
      if @education.update_attributes(params[:education])
        format.html { redirect_to @education, :notice => 'Education was successfully updated.' }
        format.json { render :json => @education }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @education.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education = Education.find(params[:id])
    @education.destroy

    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { render :json => @education }
    end
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.haml
= form_for(@education) do |f|
  - if @education.errors.any?
    #error_explanation
      %h2= "#{pluralize(@education.errors.count, "error")} prohibited this education from being saved:"
      %ul
        - @education.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :school_name
    = f.text_field :school_name

  .field
    = f.label :degree
    = f.text_field :degree

  .field
    = f.label :study_field
    = f.text_field :study_field

  .field
    = f.label :start_date
    = f.date_select :start_date,
    :start_year => Time.now.year - 50,
    :discard_day => true,
    :discard_month => true,
    :include_blank => true

  .field
    = f.label :end_date
    = f.date_select :end_date,
    :start_year => Time.now.year - 50,
    :discard_day => true,
    :discard_month => true,
    :include_blank => true

  .field.activities
    = f.label :activities
    = f.text_area :activities

  .field.notes
    = f.label :notes
    = f.text_area :notes

  .actions
    =f.submit "Submit", :value=>"Save", :class => "green-btn"

app/views/educations/edit.html.haml
#home
  %h1 Editing education
  = render 'form'

  = link_to 'Show', @education
  \|
  = link_to 'Back', educations_path

app/views/educations/index.html.haml
#home
  %h1 Listing educations

  %table
    %tr
      %th School name
      %th Degree
      %th Study field
      %th Start date
      %th End date
      %th Activities
      %th Notes
      %th
      %th
      %th

    - @educations.each do |education|
      %tr
        %td= education.school_name
        %td= education.degree
        %td= education.study_field
        %td= education.start_date
        %td= education.end_date
        %td= education.activities
        %td= education.notes
        %td= link_to 'Show', education
        %td= link_to 'Edit', edit_education_path(education)
        %td= link_to 'Destroy', education, :confirm => 'Are you sure?', :method => :delete

  %br

  = link_to 'New Education', new_education_path

app/views/educations/new.html.haml
#home
  %h1 New education

  = render 'form'

  = link_to 'Back', educations_path

app/views/educations/show.html.haml
#home
  #notice=  notice

  %p
    %strong School name:
    = @education.school_name

  %p
    %strong Degree:
    = @education.degree

  %p
    %strong Study field:
    = @education.study_field

  %p
    %strong Start date:
    = @education.valid_year(@education.start_date)

  %p
    %strong End date:
    = @education.valid_year(@education.end_date)

  %p
    %strong Activities:
    = @education.activities

  %p
    %strong Notes:
    = @education.notes


  = link_to 'Edit', edit_education_path(@education)
  \|
  = link_to 'Back', educations_path